name: DVHSiegeItem
version: '$version'
main: com.danvhae.minecraft.siege.item.DVHSiegeItem
api-version: 1.12.2
authors: [해야, 보라비, 단츄, 로미오는줄리엣]
description: 꿈뻑 공성전 콘텐츠 아이템 제어 플러그인
website: https:cafe.naver.com/danvhae
depend: [Vault, DVHSiegeCore, MagicSpells]

commands:
  siege-spell-item:
    description: 스펠 아이템 생성 명령어
  ticket-item:
    description: 각종 티켓 생성 및 지급 명령어
  exp-coin:
    description: 경험치 코인 지급 명령어
